### ISSUE TITLE
Not working with CentOS7.7 kernel 3.10

### ISSUE THREAD

**Issue by pufferbatterie** [brettwooldridge/jnb-ping#7]
Im trying to get this lib working on CentOS7.

With the shipped kernel 3.10.0-1062.el7.x86_64 i don't get a response or any errors.
With the kernel 4.4.220-1.el7.elrepo.x86_64 (updated via elrepo install kernel-lt) it works fine.

Both setups have the necessary kernel parameter net.ipv4.ping_group_range set to "0 0" running as root.

Not sure if this is a issue of jnb-ping but i am thankful for any hints.

**Comment by brettwooldridge** [comment]
It is possible that the kernel was compiled [without support for it](https://fedoraproject.org/wiki/Changes/EnableSysctlPingGroupRange).  Or are you running in a container, like LXC?

**Comment by pufferbatterie** [comment]
I am running the app as the root user, no namespaces etc. and there is no firewall in place.
The newer kernel with net.ipv4.ping_group_range set to allow it for root works fine.

I did not find any related kernel config paramter which compiles this feature. As far as i understand the sysctl for this is there since 2.6 and also can be set and read on both kernels.

However the config shows not up in the procfs (/proc/sys/net/ipv4/ping_group_range).
This should not be a problem since it works on the newer kernel where it is also missing.

Since centos kernel is not easy to obtain i found a slightly older one [here](https://github.com/spacex/kernel-centos7/blob/master/net/ipv4/Kconfig ) where IPPROTO_ICMP is already present in af_inet.c. 

If some (extra) config is needed i would kindly suggest listing that fact in the README.

**Comment by brettwooldridge** [comment]
Note added to README.md.
